### ISSUE TITLE
Could you please upload the SPM weights for versions 2.x and XL?

### ISSUE THREAD

**Issue by chkimmmmm** [Con6924/SPM#4]
Hello,

I'm currently working with your model and would greatly benefit from having the weights for versions 2.x and XL. 
Could you please upload these resources?

Thank you for your assistance!

**Comment by Con6924** [comment]
Sorry for the late response. We will release the weights in this month. However, the uploaded weights might only contains in which the experiments of our paper includes. If SPMs for other concepts are required, we suggests a trial on our released training code.

**Comment by mychina75** [comment]
We have to train different model for different concepts, right?
