### ISSUE TITLE
How to calculate the Non-Target FID using the code?

### ISSUE THREAD

**Issue by anseryuer** [Con6924/SPM#8]
Hi, I really appreciate your paper and I am doing some further playing and testing with it. 

In your paper, your mentioned: 

2) Frechet ´Inception Distance (FID) [12] for non-target concepts. It is calculated between the generations of the erased model and the original DM, with a larger FID value demonstrating more severe generation alteration after erasing.

However, it is not quite clear for me on the workflow of generating image and FID calculation. What is the number and prompt of the image used to generate? Is should be the same number of images for calculating the Clip Score and Clip Accuracy right? 

Also, it seems that there is also some difference between the object forgetting and style forgetting. For snoopy, it should be using the clip template to generate 800 images and for van gogh it should be the van gogh artist prompt csv data and using the artwork task arg to generate 400 images right?

Do you have detailed instructions on how to do this? Thank you for your help!

**Comment by anseryuer** [comment]
Also, to get the FID for style unlearning in the paper, all I need is to calculate the fid between 20 sd base model vs 20 finetuned generated model for the FID right?

And also the doing the same for object unlearning with the 80 images generated by the template prompts.

**Comment by anseryuer** [comment]
Also, to get the FID for style unlearning in the paper, all I need is to calculate the fid between 20 sd base model vs 20 finetuned generated model for the FID right?

And also the doing the same for object unlearning with the 80 images generated by the template prompts.

**Comment by Con6924** [comment]
The generation for the non-target concepts follow the protocol the same as target concepts. 

> Also, it seems that there is also some difference between the object forgetting and style forgetting. For snoopy, it should be using the clip template to generate 800 images and for van gogh it should be the van gogh artist prompt csv data and using the artwork task arg to generate 400 images right?

Yes, and you might try on the `evaluate_task.py` with `general` or `art` task for these evaluations.
