### ISSUE TITLE
Evaluation dataset

### ISSUE THREAD

**Issue by Atmyre** [Con6924/SPM#9]
Hello. I have a question regarding evaluation procedure. In the paper I see the following:

`In order to holistically assess the generation capability after erasing, we employ 80 templates proposed in CLIP [33] to augment text prompts. A concept to be evaluated is incorporated into 80 templates, with each template yielding 10 images`

But I wasn't able to find any information on where I can find these exact templates and 10 concepts that you use. Could you please point me to where I can find it, so that I can compare my results to your work?

**Comment by Con6924** [comment]
Sorry for the unclear contents. 
These templates could be found at [CLIP](https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb) and "with each template yielding 10 images" means each prompt is used to generate on 10 different seeds.

**Comment by Atmyre** [comment]
Thanks to pointing to where 80 templates are!

But may I also ask whick exactly concepts did you use to put into these templates? And, if possible, which seeds you used? It is important to calculate metrics consistent with yours

**Comment by Con6924** [comment]
> Thanks to pointing to where 80 templates are!
> 
> But may I also ask whick exactly concepts did you use to put into these templates? And, if possible, which seeds you used? It is important to calculate metrics consistent with yours

The concepts used for calculating these metrics are the target concept (e.g. Snoopy) and the corresponding non-targets (e.g. Mickey, Spongebob, Dog, Legislator, etc. ). The seed is 0 by default.
